# Spring application
spring.application.name=smart-campus

<<<<<<< HEAD
# Database connection (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus_db
spring.datasource.username=root
spring.datasource.password=21345
=======
server.port=8081

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=500MB

spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus
spring.datasource.username=root
spring.datasource.password=Anu@20021214
>>>>>>> origin/Development
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
<<<<<<< HEAD
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Server
server.port=8086
=======

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anuradhawork123@gmail.com
spring.mail.password=umae tfzt zkli wjow
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jwt.secret=Y2hhbGxlbmdlVG9pcmu0ZU41bGxQcmVkaWN0YWJsZVNlY3JldEtleQ==

spring.cookie.secure=false
spring.cookie.same-site=Lax

spring.security.oauth2.client.registration.google.client-id=855464253088-riio2io6f23btt41tevr237fo2mgupbi.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google
>>>>>>> origin/Development
